# Generated by Django 3.1.7 on 2021-03-22 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='None', max_length=50, verbose_name='ФИО')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(default='None', max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации')),
                ('doctor_type', models.CharField(default='', max_length=30, verbose_name='Тип Врача')),
                ('payed_status', models.BooleanField(verbose_name='Оплатил или нет?')),
                ('used_services', models.CharField(default='', max_length=50, verbose_name='Использованные услуги')),
                ('total_sum', models.CharField(default='', max_length=50, verbose_name='Итого')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.patients')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
