# Generated by Django 3.1.7 on 2021-03-29 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='None', max_length=50, verbose_name='ФИО')),
                ('speciality', models.CharField(default='', max_length=50, verbose_name='Специальность')),
                ('qualification', models.CharField(default='', max_length=50, verbose_name='Квалификация')),
                ('phone', models.CharField(default='None', max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(default='None', max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=20, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Treaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(default='', max_length=50, verbose_name='Специальность')),
                ('disease', models.CharField(default='', max_length=30, verbose_name='Болезнь')),
                ('discharge', models.TextField(default='', verbose_name='Выписка')),
            ],
            options={
                'verbose_name': 'Стандартное лечение',
                'verbose_name_plural': 'Стандартные лечения',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=20, verbose_name='Роль')),
                ('login', models.CharField(default='', max_length=50, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль')),
                ('create', models.BooleanField(default=False, verbose_name='Создание')),
                ('delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('edit', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('view', models.BooleanField(default=False, verbose_name='Просмотр')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации')),
                ('payment_status', models.BooleanField(verbose_name='Оплатил или нет?')),
                ('used_services', models.CharField(default='', max_length=70, verbose_name='Использованные услуги')),
                ('total_sum', models.IntegerField(verbose_name='Итоговая сумма')),
                ('discharge', models.TextField(default='', verbose_name='Выписка')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.patients')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
