# Generated by Django 3.1.7 on 2021-03-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='None', max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(default='None', max_length=13, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='None', max_length=50, verbose_name='ФИО')),
                ('doctor_type', models.CharField(default='None', max_length=30, verbose_name='Тип Врача')),
                ('payed_status', models.BooleanField(default='False', verbose_name='Оплатил или нет?')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Итого')),
                ('files', models.FilePathField(path='/home/documents')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.patient')),
            ],
        ),
    ]
