# Generated by Django 3.1.7 on 2021-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
