# Generated by Django 3.1.7 on 2021-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_users_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайслист', 'verbose_name_plural': 'Прайслист'},
        ),
        migrations.RemoveField(
            model_name='records',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='records',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время регистрации'),
        ),
    ]
