# Generated by Django 3.1.7 on 2021-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210321_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='records',
            name='files',
        ),
        migrations.AlterField(
            model_name='records',
            name='doctor_type',
            field=models.CharField(default='', max_length=30, verbose_name='Тип Врача'),
        ),
        migrations.AlterField(
            model_name='records',
            name='full_name',
            field=models.CharField(default='', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='records',
            name='payed_status',
            field=models.BooleanField(verbose_name='Оплатил или нет?'),
        ),
        migrations.AlterField(
            model_name='records',
            name='total_sum',
            field=models.CharField(default='', max_length=50, verbose_name='Итого'),
        ),
    ]
