# Generated by Django 3.1.7 on 2021-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210322_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
