# Generated by Django 3.1.7 on 2021-03-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20210322_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='payed_status',
            new_name='payment_status',
        ),
    ]
