# Generated by Django 3.1.7 on 2021-04-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20210401_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='payment_status',
            field=models.BooleanField(verbose_name='Оплатил'),
        ),
    ]
