# Generated by Django 3.1.7 on 2021-04-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20210401_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_patients', to='control.patients'),
        ),
    ]
