# Generated by Django 3.1.7 on 2021-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20210401_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
