# Generated by Django 3.2 on 2021-05-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20210430_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.doctors')),
            ],
            options={
                'verbose_name': 'Прайслист',
                'verbose_name_plural': 'Прайслист',
            },
        ),
        migrations.DeleteModel(
            name='Pricelist',
        ),
    ]
