# Generated by Django 3.2 on 2021-05-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_serviceslist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treaments',
            name='speciality',
        ),
        migrations.AddField(
            model_name='treaments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.doctors'),
        ),
    ]
