# Generated by Django 3.2 on 2021-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_treaments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='disease',
            field=models.TextField(default='', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='records',
            name='discharge',
            field=models.TextField(default='', verbose_name='Лечение'),
        ),
    ]
